dd_0:
	hspice t_su_dd_0_test.sp > t_su_dd_0_test.out && grep "t_.*=" t_su_dd_0_test.out

dd_1:
	hspice t_su_dd_1_test.sp > t_su_dd_0_test.out && grep "t_.*=" t_su_dd_0_test.out

opt_0:
	hspice t_su_opt_0_test.sp > t_su_opt_0_test.out && grep "t_.*=" t_su_opt_0_test.out

opt_1:
	hspice t_su_opt_1_test.sp > t_su_opt_1_test.out && grep "t_.*=" t_su_opt_1_test.out

